CREATE TABLE books (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  blurb TEXT,
  chapter_order INTEGER[] DEFAULT '{}' NOT NULL,
  default_book BOOLEAN UNIQUE,
  published BOOLEAN,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_published TIMESTAMP,
  date_modified TIMESTAMP,
  CONSTRAINT must_be_published CHECK(CASE WHEN default_book = true THEN published = true END)
);
