CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  perms BOOLEAN,
  profile_image INTEGER CHECK (profile_image >= 0 AND profile_image <= 5), -- can choose one of 6 images, stores as index of said image
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);